Update checksums-build.yml

diff --git a/.github/workflows/checksums-build.yml b/.github/workflows/checksums-build.yml
--- a/.github/workflows/checksums-build.yml
+++ b/.github/workflows/checksums-build.yml
@@ -99,7 +99,7 @@ jobs:
 
       - name: Assert manifest exists
         run: |
-          test -f :$MAN" || { echo "::error ::Manifest not found at $MAN"; exit 1; }
+          test -f $MAN" || { echo "::error ::Manifest not found at $MAN"; exit 1; }
           
       - name: Show diff
         run: |
